version: "3.9"
services:
  app:
    build: ./php
    volumes:
      - ../src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ../src:/data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: